version: "3.8"
services:
    app:
        container_name: SpringBlogApp
        build: .
        ports:
            - '8080:8080'
        networks:
            - spring_blog_app_network
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - '27017:27017'
        volumes:
            - data:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=rootuser
            - MONGO_INITDB_ROOT_PASSWORD=rootpass
        networks:
            - spring_blog_app_network
volumes:
    data: {}
networks:
    spring_blog_app_network:
        driver: bridge
